version: '3'

services:

  db:
    restart: always
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - db_nw
  web_app:
    build: .
    command: /bin/sh -c "gunicorn izu.wsgi:application --bind 0.0.0.0:8000 && python manage.py migrate"
    volumes:
      - .:/var/www/app/
    depends_on:
      - db
    # env_file: .env
    networks:
      - db_nw
      - web_app_nw
      - smtp_nw

  nginx:
    build: ./nginx
    volumes:
      - ./static:/var/www/app/static
      - ./media:/var/www/app/media
    ports:
      - "8000:80"
    depends_on:
      - web_app
    restart: always
    networks:
      - web_app_nw



  smtp:
    build:
      context: ./docker-smtp
    restart: always
    ports:
     - "587:587"
    # env_file: .env
    networks:
      - smtp_nw
      - web_app_nw

volumes:
  db_data:


networks:
  db_nw:
    driver: bridge
  web_app_nw:
    driver: bridge
  smtp_nw:
    driver: bridge